<?php

/**
 * @file
 * Sets up the S3fsStreamWrapper class to be used as a Drupal file system.
 */

/**
 * The version number of the current release.
 */
define('S3FS_VERSION', '8.x-alpha14');


/**
 * Implements hook_stream_wrappers().
 */
function s3fs_stream_wrappers()
{
    return array(
        's3' => array(
            'name'        => 'S3 File System',
            'class'       => 'Drupal\s3fs\S3fsStreamWrapper',
            'description' => \Drupal::translation()->translate('Amazon Simple Storage Service'),
        ),
    );
}

/**
 * Implements hook_help().
 */
function s3fs_help($path, $arg)
{
    $actions  = 'admin/config/media/s3fs/actions';
    $settings = 'admin/config/media/s3fs/settings';
    if($path == $settings)
    {
        $msg = \Drupal::translation()->translate('To perform actions, visit the !link', array('!link' => l(t('actions page'), $actions)));

        return "<p>$msg</p>";
    }
    elseif($path == $actions)
    {
        $msg = \Drupal::translation()->translate('These are the actions that you can perform upon S3 File System.');
        $msg .= '<br>' . \Drupal::translation()->translate('To change your settings, visit the !link.', array('!link' => l(t('settings page'), $settings)));

        return "<p>$msg</p>";
    }
}
