<?php

/**
 * @file
 * Sets up the S3fsStreamWrapper class to be used as a Drupal file system.
 */
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * The version number of the current release.
 */
define('S3FS_VERSION', '8.x-alpha14');


/**
 * Implements hook_stream_wrappers().
 * @see hook_stream_wrappers()
 */
function s3fs_stream_wrappers()
{
    $translator = \Drupal::translation();

    return array(
        's3' => array(
            'name'        => 'S3 File System',
            'class'       => 'Drupal\s3fs\S3fsStreamWrapper',
            'description' => $translator->translate('Amazon Simple Storage Service'),
        ),
    );
}

/**
 * Implements hook_help().
 *
 * @see hook_help()
 *
 * @param string              $route_name
 * @param RouteMatchInterface $route_match
 *
 * @return string
 */
function s3fs_help($route_name, RouteMatchInterface $route_match)
{
    $translator = \Drupal::translation();
    $linker     = \Drupal::linkGenerator();

    if($route_name == 's3fs.actions')
    {
        $msg = $translator->translate('To perform actions, visit the !link',
            array('!link' => $linker->generateFromLink(Link::createFromRoute($translator->translate('actions page'), 's3fs.actions'))));

        return "<p>$msg</p>";
    }
    elseif($route_name == 's3fs.settings')
    {
        $msg = $translator->translate('These are the actions that you can perform upon S3 File System.');
        $msg .= '<br>';
        $msg .= $translator->translate('To change your settings, visit the !link.',
            array(
                '!link' => $linker->generateFromLink(Link::createFromRoute($translator->translate('settings page'), 's3fs.settings'))
            )
        );

        return "<p>$msg</p>";
    }
}
